wandb_version: 1

D:
  desc: null
  value: 582
K:
  desc: null
  value: 2
L:
  desc: null
  value: 1
M:
  desc: null
  value: 4
Mu_init:
  desc: null
  value: "[[-0.1188803   0.81473185  0.68394419 ...  0.          0.\n   0.       \
    \ ]]"
N:
  desc: null
  value: 845
Sigma_init:
  desc: null
  value: '[[1. 1. 1. ... 1. 1. 1.]]'
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1647357694
    t:
      3:
      - 3
      - 13
      - 16
      4: 3.7.3
      5: 0.12.11
      8:
      - 1
      - 5
architecture:
  desc: null
  value:
    activations:
    - relu
    - relu
    - linear
    biases:
    - 1
    - 1
    - 1
    gamma:
    - 1.0
    hidden_layers:
    - 20
    - 20
    input_n: 4
    output_n: 2
    seed: 207
    sigma:
    - 1.0
    - 1.0
gamma:
  desc: null
  value: 1.0
num_iters:
  desc: null
  value: 2000
num_samples:
  desc: null
  value: 500
random_seed:
  desc: null
  value: 207
sigma:
  desc: null
  value: 1.0
step_size:
  desc: null
  value: 0.001
