wandb_version: 1

D:
  desc: null
  value: 582
K:
  desc: null
  value: 2
L:
  desc: null
  value: 1
M:
  desc: null
  value: 4
N:
  desc: null
  value: 845
_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1649833446
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      4: 3.7.3
      5: 0.12.14
      8:
      - 1
      - 5
architecture:
  desc: null
  value:
    activations:
    - relu
    - relu
    - linear
    biases:
    - 1
    - 1
    - 1
    gamma:
    - 1.0
    hidden_layers:
    - 20
    - 20
    input_n: 4
    output_n: 2
    seed: 207
    sigma:
    - 1.0
    - 1.0
burn_in:
  desc: null
  value: 0.5
gamma:
  desc: null
  value: 1.0
leapfrog_steps:
  desc: null
  value: 10
mass:
  desc: null
  value: 1.0
position_init:
  desc: null
  value: "[[ 0.36578869 -0.07316059  1.54376336 ...  0.          0.\n   0.       \
    \ ]]"
random_seed:
  desc: null
  value: 207
sigma:
  desc: null
  value: 1.0
step_size:
  desc: null
  value: 1.0e-05
thinning_factor:
  desc: null
  value: 1
total_samples:
  desc: null
  value: 100
